with-expecter: true
packages:
  # internal
  github.com/platform-mesh/extension-manager-operator/pkg/validation:
    config:
      dir: pkg/validation/mocks
      outpkg: mocks
    interfaces:
      ExtensionConfiguration:
        config:
          mockname: ExtensionConfiguration

  # external
  net/http:
    config:
      dir: pkg/validation/mocks
      outpkg: mocks
    interfaces:
      ResponseWriter:
        config:
          mockname: ResponseWriter
  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      dir: pkg/subroutines/mocks
      outpkg: mocks
    interfaces:
      Client:
        config:
          mockname: Client