# This rule is not used by the project extension-manager-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ui.platform-mesh.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: extension-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: providermetadata-viewer-role
rules:
- apiGroups:
  - ui.platform-mesh.io
  resources:
  - providermetadatas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ui.platform-mesh.io
  resources:
  - providermetadatas/status
  verbs:
  - get
