# This rule is not used by the project extension-manager-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the ui.platform-mesh.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: extension-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: providermetadata-editor-role
rules:
- apiGroups:
  - ui.platform-mesh.io
  resources:
  - providermetadatas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ui.platform-mesh.io
  resources:
  - providermetadatas/status
  verbs:
  - get
