apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    app.kubernetes.io/name: contentconfiguration
    app.kubernetes.io/instance: contentconfiguration-sample
    app.kubernetes.io/part-of: extension-manager-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: extension-manager-operator
  name: contentconfiguration-sample
  namespace: default
  generation: 1
spec:
  inlineConfiguration:
    contentType: yaml # can be yaml or json
    content: |
      name: overview
      luigiConfigFragment:
       data:
         nodes:
         - entityType: global
           pathSegment: mysegment
           label: Overview
           icon: mysegment
           hideFromNav: true
           defineEntity:
             id: example
           children:
           - pathSegment: overview
             label: Overview
             icon: mysegment
             url: https://fiddle.luigi-project.io/examples/microfrontends/multipurpose.html
             context:
               title: Welcome to Platform Mesh Portal
               content: " "
