// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	multierror "github.com/hashicorp/go-multierror"
	mock "github.com/stretchr/testify/mock"

	validation "github.com/platform-mesh/extension-manager-operator/pkg/validation"
)

// ExtensionConfiguration is an autogenerated mock type for the ExtensionConfiguration type
type ExtensionConfiguration struct {
	mock.Mock
}

type ExtensionConfiguration_Expecter struct {
	mock *mock.Mock
}

func (_m *ExtensionConfiguration) EXPECT() *ExtensionConfiguration_Expecter {
	return &ExtensionConfiguration_Expecter{mock: &_m.Mock}
}

// ParseContentConfiguration provides a mock function with given fields: input, contentType
func (_m *ExtensionConfiguration) ParseContentConfiguration(input []byte, contentType string) (*validation.ContentConfiguration, error) {
	ret := _m.Called(input, contentType)

	if len(ret) == 0 {
		panic("no return value specified for ParseContentConfiguration")
	}

	var r0 *validation.ContentConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string) (*validation.ContentConfiguration, error)); ok {
		return rf(input, contentType)
	}
	if rf, ok := ret.Get(0).(func([]byte, string) *validation.ContentConfiguration); ok {
		r0 = rf(input, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*validation.ContentConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = rf(input, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtensionConfiguration_ParseContentConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseContentConfiguration'
type ExtensionConfiguration_ParseContentConfiguration_Call struct {
	*mock.Call
}

// ParseContentConfiguration is a helper method to define mock.On call
//   - input []byte
//   - contentType string
func (_e *ExtensionConfiguration_Expecter) ParseContentConfiguration(input interface{}, contentType interface{}) *ExtensionConfiguration_ParseContentConfiguration_Call {
	return &ExtensionConfiguration_ParseContentConfiguration_Call{Call: _e.mock.On("ParseContentConfiguration", input, contentType)}
}

func (_c *ExtensionConfiguration_ParseContentConfiguration_Call) Run(run func(input []byte, contentType string)) *ExtensionConfiguration_ParseContentConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(string))
	})
	return _c
}

func (_c *ExtensionConfiguration_ParseContentConfiguration_Call) Return(_a0 *validation.ContentConfiguration, _a1 error) *ExtensionConfiguration_ParseContentConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExtensionConfiguration_ParseContentConfiguration_Call) RunAndReturn(run func([]byte, string) (*validation.ContentConfiguration, error)) *ExtensionConfiguration_ParseContentConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: _a0, _a1
func (_m *ExtensionConfiguration) Validate(_a0 []byte, _a1 string) (string, *multierror.Error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 string
	var r1 *multierror.Error
	if rf, ok := ret.Get(0).(func([]byte, string) (string, *multierror.Error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func([]byte, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]byte, string) *multierror.Error); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*multierror.Error)
		}
	}

	return r0, r1
}

// ExtensionConfiguration_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ExtensionConfiguration_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - _a0 []byte
//   - _a1 string
func (_e *ExtensionConfiguration_Expecter) Validate(_a0 interface{}, _a1 interface{}) *ExtensionConfiguration_Validate_Call {
	return &ExtensionConfiguration_Validate_Call{Call: _e.mock.On("Validate", _a0, _a1)}
}

func (_c *ExtensionConfiguration_Validate_Call) Run(run func(_a0 []byte, _a1 string)) *ExtensionConfiguration_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(string))
	})
	return _c
}

func (_c *ExtensionConfiguration_Validate_Call) Return(_a0 string, _a1 *multierror.Error) *ExtensionConfiguration_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExtensionConfiguration_Validate_Call) RunAndReturn(run func([]byte, string) (string, *multierror.Error)) *ExtensionConfiguration_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateEntityTypes provides a mock function with given fields: input, contentType, registry
func (_m *ExtensionConfiguration) ValidateEntityTypes(input []byte, contentType string, registry *validation.EntityTypeRegistry) *multierror.Error {
	ret := _m.Called(input, contentType, registry)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEntityTypes")
	}

	var r0 *multierror.Error
	if rf, ok := ret.Get(0).(func([]byte, string, *validation.EntityTypeRegistry) *multierror.Error); ok {
		r0 = rf(input, contentType, registry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*multierror.Error)
		}
	}

	return r0
}

// ExtensionConfiguration_ValidateEntityTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEntityTypes'
type ExtensionConfiguration_ValidateEntityTypes_Call struct {
	*mock.Call
}

// ValidateEntityTypes is a helper method to define mock.On call
//   - input []byte
//   - contentType string
//   - registry *validation.EntityTypeRegistry
func (_e *ExtensionConfiguration_Expecter) ValidateEntityTypes(input interface{}, contentType interface{}, registry interface{}) *ExtensionConfiguration_ValidateEntityTypes_Call {
	return &ExtensionConfiguration_ValidateEntityTypes_Call{Call: _e.mock.On("ValidateEntityTypes", input, contentType, registry)}
}

func (_c *ExtensionConfiguration_ValidateEntityTypes_Call) Run(run func(input []byte, contentType string, registry *validation.EntityTypeRegistry)) *ExtensionConfiguration_ValidateEntityTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(string), args[2].(*validation.EntityTypeRegistry))
	})
	return _c
}

func (_c *ExtensionConfiguration_ValidateEntityTypes_Call) Return(_a0 *multierror.Error) *ExtensionConfiguration_ValidateEntityTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExtensionConfiguration_ValidateEntityTypes_Call) RunAndReturn(run func([]byte, string, *validation.EntityTypeRegistry) *multierror.Error) *ExtensionConfiguration_ValidateEntityTypes_Call {
	_c.Call.Return(run)
	return _c
}

// WithSchema provides a mock function with given fields: _a0
func (_m *ExtensionConfiguration) WithSchema(_a0 []byte) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for WithSchema")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExtensionConfiguration_WithSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithSchema'
type ExtensionConfiguration_WithSchema_Call struct {
	*mock.Call
}

// WithSchema is a helper method to define mock.On call
//   - _a0 []byte
func (_e *ExtensionConfiguration_Expecter) WithSchema(_a0 interface{}) *ExtensionConfiguration_WithSchema_Call {
	return &ExtensionConfiguration_WithSchema_Call{Call: _e.mock.On("WithSchema", _a0)}
}

func (_c *ExtensionConfiguration_WithSchema_Call) Run(run func(_a0 []byte)) *ExtensionConfiguration_WithSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ExtensionConfiguration_WithSchema_Call) Return(_a0 error) *ExtensionConfiguration_WithSchema_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExtensionConfiguration_WithSchema_Call) RunAndReturn(run func([]byte) error) *ExtensionConfiguration_WithSchema_Call {
	_c.Call.Return(run)
	return _c
}

// NewExtensionConfiguration creates a new instance of ExtensionConfiguration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExtensionConfiguration(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExtensionConfiguration {
	mock := &ExtensionConfiguration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
