name: api-release

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

permissions:
  contents: write

jobs:
  create-api-version:
    uses: platform-mesh/.github/.github/workflows/job-create-version.yml@main
    secrets: inherit
    with:
      apiPackagePath: api
