name: api-release

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

permissions:
  contents: read

jobs:
  create-api-version:
    uses: platform-mesh/.github/.github/workflows/job-create-version.yml@9ddacafbe3260312cb1cc3f9974ad2fece8effe0 # main
    secrets: inherit
    permissions:
      contents: write
    with:
      apiPackagePath: api
