name: job-docker-build-push
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      version:
        required: false
        type: string
        default: ''
      release_branch:
        required: false
        type: string
        default: 'main'
      multiarch:
        required: false
        type: boolean
        default: false
    secrets:
      TECH_PLATFORM_TOKEN:
        required: true

jobs:
  dockerBuild:
    uses: platform-mesh/.github/.github/workflows/job-docker-build-push.yml@main
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ inputs.version }}
      release_branch: ${{ inputs.release_branch }}
      multiarch: ${{ inputs.multiarch }}
    secrets: inherit
