name: job-create-version
on:
  workflow_call:
    inputs:
      apiPackagePath:
        required: false
        type: string
        default: ''
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.createVersion.outputs.version }}
    secrets:
      TECH_PLATFORM_TOKEN:
        required: true

jobs:
  createVersion:
    uses: platform-mesh/.github/.github/workflows/job-create-version.yml@main
    secrets: inherit
    with:
      apiPackagePath: ${{ inputs.apiPackagePath }}
