name: job-golang-lint
on:
  workflow_call:
    inputs:
      useTask:
        required: false
        type: boolean
        default: false
    secrets:
      TECH_PLATFORM_TOKEN:
        required: true

jobs:
  lint:
    uses: platform-mesh/.github/.github/workflows/job-golang-lint.yml@main
    with:
      useTask: ${{ inputs.useTask }}
    secrets: inherit
