name: job-auto-labeler
on:
  workflow_call:
    secrets:
      TECH_PLATFORM_TOKEN:
        required: true

jobs:
  auto-labeler:
    uses: platform-mesh/.github/.github/workflows/job-auto-labeler.yml@main
    secrets: inherit
